Add controllers
ivan-nizalzov/java-shareit pull request #1
Opened 2023-03-24 18:43 UTC by ivan-nizalzov

Код написан в стиле "Feature layout".  
Созданы две фичи:
- Item;
- User.
Для каждой фичи созданы DTO-мапперы, хранение данных реализовано в памяти приложения (InMemory), также реализованы соответствующие Service, Model, Controller, Repository.
Каркас приложения реализован с помощью Spring Boot 2.

2023-03-25 11:41 UTC, andrew-larkin requested changes
Привет! Очень хороший старт, остается внести несколько правок и будем готовы двигаться дальше.

2023-03-25 11:41 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public ItemDto createItem(@RequestHeader("X-Sharer-User-Id") Long userId,
Давай для этого приложения добавим новый класс-обертку для методов контроллера ResponseEntity - он возвращает не только json, но и http-статус, что довольно удобно. Будет выглядеть как-то так:
return ResponseEntity.ok().body(itemService.createItem(itemDto, userId)); 
Для всех методов во всех контроллерах стоит его добавить

2023-03-25 11:41 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/dto/ItemDtoMapper.java
> +public class ItemDtoMapper {
для этого приложения также давай добавим библиотеку mapStruct - она используется на всех реальных проектах, будет очень полезно ее изучить

2023-03-25 11:41 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private Long ownerId;
тут стоит использовать User

2023-03-25 11:41 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
> +    private final UserService userService;
тоже добавить ResponseEntity

2023-03-27 20:26 UTC, ivan-nizalzov commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public ItemDto createItem(@RequestHeader("X-Sharer-User-Id") Long userId,
Добавил библиотеку ResponseEntity

2023-03-27 20:27 UTC, ivan-nizalzov commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private Long ownerId;
Исправил

2023-03-27 20:27 UTC, ivan-nizalzov commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
> +    private final UserService userService;
ResponseEntity добавил

2023-03-28 07:20 UTC, merged