Add item requests
ivan-nizalzov/java-shareit pull request #3
Opened 2023-05-09 23:27 UTC by ivan-nizalzov

1) added new Entity - ItemRequest;
2) added mock-tests

2023-05-13 21:40 UTC, andrew-larkin requested changes
Привет! Хорошо, новый функционал внедрен, тесты тоже написано достаточно качественно. Местами нужно избавиться от ссылок на сущности в dto и еще несколько правок внести и приложение будет готово.

2023-05-13 21:40 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    private Item item;
внутри dto не стоит использовать сущности БД

2023-05-13 21:40 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/mapper/BookingMapper.java
> +    default BookingDto toBookingDto(Booking booking) {
весь этот маппинг можно сделать с помощью аннотаций @Mapping

2023-05-13 21:40 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    @Query(" select b from Booking b join User as u on b.booker = u.id " +
@Repository - над всеми репозиториями

2023-05-13 21:40 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private Long requestId;
кажется, здесь стоит использовать сущность ItemRequest

2023-05-13 21:40 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
> +    private List<Item> items;
здесь тоже - не стоит использовать сущности

2023-05-13 21:40 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +    private Long requestorId;
User

2023-05-13 21:40 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    /*public UserDto(Long id) {
акомментированный код удаляем

2023-05-13 21:40 UTC, andrew-larkin commented on src/main/resources/application.properties
> +#spring.config.activate.on-profile=default
закомментированные строки удаляем

2023-05-14 12:45 UTC, ivan-nizalzov commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    private Item item;
Исправил

2023-05-14 12:46 UTC, ivan-nizalzov commented on src/main/java/ru/practicum/shareit/booking/mapper/BookingMapper.java
> +    default BookingDto toBookingDto(Booking booking) {
Переделал все мапперы, вместо дефолтных методов использую аннотацию @mapping

2023-05-14 12:46 UTC, ivan-nizalzov commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    @Query(" select b from Booking b join User as u on b.booker = u.id " +
done

2023-05-14 12:47 UTC, ivan-nizalzov commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private Long requestId;
Поправил

2023-05-14 12:47 UTC, ivan-nizalzov commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +    private Long requestorId;
Поправил

2023-05-14 12:47 UTC, ivan-nizalzov commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    /*public UserDto(Long id) {
Перепроверил код - закомментированные строчки удалил

2023-05-14 12:47 UTC, ivan-nizalzov commented on src/main/resources/application.properties
> +#spring.config.activate.on-profile=default
Done

2023-05-14 15:45 UTC, ivan-nizalzov commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private Long requestId;
Пришлось вернуть requestId, т.к. в тестах Постмана требуется наличие поля "request_id".
`pm.test("Test item 'requestId' field", function () {
    var jsonData = pm.response.json();
    pm.expect(jsonData).to.have.property('requestId');
    pm.expect(jsonData.requestId, '"requestId" must be "1"').to.eq(1);
});
`

2023-05-14 20:13 UTC, merged