feat: added docker
ivan-nizalzov/java-shareit pull request #4
Opened 2023-05-17 23:33 UTC by ivan-nizalzov

- added modules (shareit-gateway and shareit-server);
- added docker

2023-05-19 07:20 UTC, andrew-larkin requested changes
Привет! В целом, работа практически готова - требуется внести несколько правок по коду и сделать сборку зеленой, а также убедиться, что при запуске docker-compose контейнеры не падают. Еще из таких моментов - если останется время, стоит переписать дефолтные методы в маппере (например, для BookingMapper) на обычные с использованием аннотаций @Mapping.

2023-05-19 07:20 UTC, andrew-larkin commented on docker-compose.yml
> +    ports:
для БД стоит настроить еще и volumes

2023-05-19 07:20 UTC, andrew-larkin commented on docker-compose.yml
> +    image: shareit-server-image
тут стоит добавить настройку restart on failure

2023-05-19 07:20 UTC, andrew-larkin commented on gateway/src/main/resources/application.properties
> +#server.port=${GATEWAY_PORT}
закомментированный код удаляем везде

2023-05-19 07:20 UTC, andrew-larkin commented on server/src/main/java/ru/practicum/shareit/user/controller/UserController.java
> +    public ResponseEntity<UserDto> create(@RequestBody UserDto userDto) {
коммент не относится напрямую сюда, но в нужном месте не получается оставить: в папке request неоходимо переименовать папку service (сейчас она называестся servicce). А второе - после обсуждения с другими ревьюверами мы договорились, что сервисы нельзя внедрять в другие сервисы. Такое у тебя есть, например, в itemService - внедряется userService. Используй userRepository

2023-05-19 07:20 UTC, andrew-larkin commented on server/src/main/resources/application.properties
> +#server.port=${SERVER_PORT}
закомментированный код удаляем

2023-05-21 19:54 UTC, ivan-nizalzov commented on docker-compose.yml
> +    ports:
Добавил

2023-05-21 19:54 UTC, ivan-nizalzov commented on docker-compose.yml
> +    image: shareit-server-image
Добавил (restart)

2023-05-21 19:54 UTC, ivan-nizalzov commented on gateway/src/main/resources/application.properties
> +#server.port=${GATEWAY_PORT}
убрал

2023-05-21 19:54 UTC, ivan-nizalzov commented on server/src/main/java/ru/practicum/shareit/user/controller/UserController.java
> +    public ResponseEntity<UserDto> create(@RequestBody UserDto userDto) {
Поменял, теперь во всех сервисах у меня Repository

2023-05-21 19:55 UTC, ivan-nizalzov commented on server/src/main/resources/application.properties
> +#server.port=${SERVER_PORT}
done

2023-05-22 17:08 UTC, merged